apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-user
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: backend-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}